#对外配置服务端口
server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    #active属性值为 如果为native则表示从本地读取配置文件
    active: dev
  #例如:cloud:
      #    config:
      #      server:
      #        native:
      #          search-locations: classpath:/shared
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/r4jay/springcloud.git
          #uri: git@github.com:r4jay/springcloudlearning.git
          #配置仓库路径
          searchPaths: config
          #访问git仓库的用户名
          username: r4jay
          #访问git仓库的用户密码
          password: xt193429
      #配置仓库的分支
      label: master


eureka:
  instance:
    #SpringCloud版本升级为Finchley.RELEASE    改为ipAddress ip-address
    hostname: ${spring.cloud.client.ip-address}
    #InstanceId: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #security:
      #enabled: false

#如果启用消息总线的话 需加入如下配置
#说明:Spring Boot 1.5.X 以上默认开通了安全认证，所以需要在配置文件中application.yml 中添加如下配置以 蒋 /actuator/refresh 这个Endpoint暴露出来
management:
  endpoints:
    #此参数决定了，其他client 需要加上 web依赖,即：spring-boot-starter-web 因为主pom里已添加，所以其他子项目就不需要添加了
    web:
      exposure:
        #bus-refresh
        include: bus-refresh