spring:
  application:
    name: eurekaclient
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true

#  此配置节点用于 开启支撑手动刷新远程git 配置文件
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh