
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#server.port 为Feign对外访问接口
server:
  port: 8081
spring:
  application:
    name: feign

#开启熔断器
feign:
  hystrix:
    enabled: true
debug: true